version: 2.1
orbs:
  node: circleci/node@1.1.6

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm run build
            - run: npm
      - attach_workspace:
        at: /tmp/workspace
      - store_artifacts:
          path: /tmp/workspace/bundle-sizes.json
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - bundle-sizes.json
workflows:
  build-and-test:
    jobs:
      - build-and-test
